### ISSUE TITLE
Increase frequency of Renovate to daily

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#120]
Currently we are running renovate weekly. Renovate has a system by which it does not open more than 2 PRs (default value) at a time, so even if we run it more frequently it won't flood our PRs. If we fall into this and then we just run weekly, it will take a while until we close various PR (a month to close 8 dependency updates), which may be too much.

* Configure renovate to run daily.

**Comment by skoved** [comment]
I'm adding security vulnerability checks to the renovate config so I can grab this as well while I'm at it
