### ISSUE TITLE
resolve issues with golangci-lint errcheck

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#125]
the function calls in this code block return errors that are not checked

https://github.com/kubearchive/kubearchive/blob/main/cmd/operator/internal/controller/kubearchiveconfig_controller.go#L54

this causes golangci-lint to fail. For now golangci-lint ignores that file. We should fix the code so that we can continue to run golangci-lint on this file

**Comment by skoved** [comment]
@ggallen PTAL

**Comment by rh-hemartin** [comment]
Do we know how this passed in the first place? Could you track it down?

**Comment by skoved** [comment]
I'll look into why this happened after I wrap up the sink stuff I have in progress

**Comment by rh-hemartin** [comment]
I think it was introduced before we had checks, when we introduced the whole operator code inherited from the operator-sdk boilerplate.
