### ISSUE TITLE
Get the real plural name from the CRD, rather than blindly appending "s".

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#136]
The configuration of the role required by `ApiServerSource` need so know the plural name of the resource to be configured correctly. Currently, the code just blindly appends an "s" to the kind.  It works, but it's not the correct solution.

The operator needs to take the API version and kind provided in the `KubeArchiveConfig` and look up the associated resource to retrieve the correct plural name.

This is happening on [this line](https://github.com/kubearchive/kubearchive/blob/main/cmd/operator/internal/controller/kubearchiveconfig_controller.go#L160).

**Comment by ggallen** [comment]
The operator framework provides a client to make kubernetes calls from go, which is what I plan to use when and if I figure it out.

**Comment by rh-hemartin** [comment]
Remember to implement (or add a TODO for implementing) a cache. Also if it comes to it, we can store the singular on the database, as we have that information in the events that the ApiServerSource sends us.

**Comment by ggallen** [comment]
The operator framework takes care of the cache.
