### ISSUE TITLE
sink adds cluster name and resource's uid

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#146]
The sink needs to add the cluster name (db field name: `cluster`) and the resource's `uid` (db field name: `cluster_uid`) to the entry it writes to the database 

related to #86

**Comment by ggallen** [comment]
> Currently we are talking about this being provided by the user in the configuration, so this should go
> into the Chart values. For something long-term we can see what multi-cluster management tools use
> for cluster identification.

I have to ask again, why do we need this information?

**Comment by rh-hemartin** [comment]
We agreed on removing `cluster_uid` and `cluster_name`, we won't go multi-cluster soon and its better to remove what we don't need.

**Comment by rh-hemartin** [comment]
Reopening so we delete the cluster_uid and cluster_name in another PR.

**Comment by rh-hemartin** [comment]
Closed in favor of #183
