### ISSUE TITLE
one ApiServerSource per namespace

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#16]
This will let will allow users to specify which resources should be archived in a namespace. 

Ex: resource a in namespace foo can be archived but resource a in namespace bar can be ignored

**Comment by maruiz93** [comment]
There are some api-resources that aren't namespaced (and CRDs can be cluster-wide too).
I think we should address the usecase of watching changes on those ones.

Based on [this issue](https://github.com/knative/eventing/issues/2892) APIServerSource should allow to watch cluster scoped resources but I'm not sure of how the APIServerSource should be configured for doing that.

Should we include an apiserversource on a predefined namespace to watch cluster-wide resources?

**Comment by ggallen** [comment]
What is the goal of this issue?  Are you looking to use helm to deploy an ApiServerSource per namespace?

If so, I would keep it simple. Just deploy the ApiServerSource to the namespace. You could optionally allow the ApiServerSource to be configured as part of the helm chart, or just deploy it with no configuration and let the user do it manually for now.  I see this as a temporary solution.

In my mind the operator should be doing all this configuration for users, and it will be able to present a simple configuration mechanism to users which it can then translate into a real ApiServerSource configuration.

**Comment by ggallen** [comment]
> Should we include an apiserversource on a predefined namespace to watch cluster-wide resources?

Should we even allow users to specify cluster-wide resources to be archived? I say no to this.

But if we do allow it at all,it would have to be done by a k9e admin, which points to us having our own ApiServerSource instance that allows this to happen.

**Comment by skoved** [comment]
> What is the goal of this issue? Are you looking to use helm to deploy an ApiServerSource per namespace?
> 
> If so, I would keep it simple. Just deploy the ApiServerSource to the namespace. You could optionally allow the ApiServerSource to be configured as part of the helm chart, or just deploy it with no configuration and let the user do it manually for now. I see this as a temporary solution.
> 
> In my mind the operator should be doing all this configuration for users, and it will be able to present a simple configuration mechanism to users which it can then translate into a real ApiServerSource configuration.

Since we don't have the operator ready yet, my idea was to modify the helm chart so that you could specify namespaces that you want to archive resources from and what resources in each namespace you are interested in and it would deploy an ApiServerSource into that namespace. I agree that this should only be temporary and the helm chart should be changed to deploy the operator once we get there

**Comment by skoved** [comment]
> > Should we include an apiserversource on a predefined namespace to watch cluster-wide resources?
> 
> Should we even allow users to specify cluster-wide resources to be archived? I say no to this.
> 
> But if we do allow it at all,it would have to be done by a k9e admin, which points to us having our own ApiServerSource instance that allows this to happen.

It seems reasonable to me to allow a cluster admin to configure k9e to archive cluster-wide resources. I would split it into a separate issue from this one though

**Comment by maruiz93** [comment]
> Should we even allow users to specify cluster-wide resources to be archived? I say no to this.

This should be a design decision.

The cluster scoped resources aren't usually for resources with a "terminated" status, but they can be used for storing configuration stuff.
I think that this can be useful for querying when was a specific configuration changed.

For example, although it is deprecated, Tekton has [ClusterTask](https://tekton.dev/docs/pipelines/tasks/#task-vs-clustertask) custom resource that may be useful to archive for the same querying/troubleshooting purposes. Tekton has other [cluster scoped custom resources](https://github.com/search?q=org%3Atektoncd+%22scope%3A+Cluster%22+%22kind%3A%22+language%3AYAML&type=code), but they are mainly used for configure the operator.

There might be other operators with other cluster scoped custom resources users might want to archive, so I'm not sure if we should limit kubearchive to archive namespaced resources, especially if there is no technical limitation for doing so.
