### ISSUE TITLE
Run `go mod tidy` on the CI

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#179]
Currently we have unused dependencies on the `go.mod` file. That raises warnings within my editor. I think it would be nice to run `go mod tidy` in our CI, so we make sure we keep the file clean. `git` has a nice option that raises an error if a file is changed in the `diff` command called `--exit-code`. The workflow would be:

* Run `go mod tidy`
* Check if go.mod has any modification and raise an error in that case.
* Check if go.sum has any modification and raise an error in that case.

**Comment by ggallen** [comment]
I thought the new tool that @skoved added to CI would already do this for us.

**Comment by skoved** [comment]
goimports only adds and removes imports from `*.go` files. When it adds an import, it uses `go.mod` to determine if there is a suitable module to import. It does not handle adding and removing modules from `go.mod`. `go mod tidy` is used for cleaning up `go.mod` and `go.sum`
