### ISSUE TITLE
panic: pq: null value in column "uuid" of relation "resource" violates not-null constraint

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#181]
I have this error when I try to initialize the database:

```
panic: pq: null value in column "uuid" of relation "resource" violates not-null constraint
```

Looks like the entries of the example resources where not updated. Do we still want to keep these around? Isn't easier to generate traffic than keeping those entries up to date?

**Comment by maruiz93** [comment]
I found them useful, as I am working in the api server I test things without generating traffic and it's easier for me to just run the script.

I also faced this issue, and I have a quick fix locally:

```
        CREATE TABLE IF NOT EXISTS public.resource (
-               "uuid" uuid PRIMARY KEY,
+               "uuid" uuid PRIMARY KEY NOT NULL,
                "api_version" varchar NOT NULL,
                "cluster" varchar NOT NULL,
-               "cluster_uid" uuid NOT NULL,
                "kind" varchar NOT NULL,
```

```
-INSERT INTO public.resource (api_version,"cluster",cluster_uid,kind,name,"namespace",resource_version,created_ts,updated_ts,cluster_deleted_ts,"data") VALUES
+INSERT INTO public.resource (api_version,"cluster",uuid,kind,name,"namespace",resource_version,created_ts,updated_ts,cluster_deleted_ts,"data") VALUES
```

And updated the uuid values to be different for each registry.

I don't know if this is what it should be but I thing we should address this issue by fixing the examples.

For now, we don't have Tekton resources in the example data but is something that we could add and make easier test the api rest alone when developing for example.

**Comment by mafh314** [comment]
In the development phase that we are now, I think it's useful to have these tests values in the DB.

**Comment by rh-hemartin** [comment]
Then let this be about fixing those issues. Thanks for  the answer.
