### ISSUE TITLE
Use k8s Unstructured instead of custom ResourceEntry when the sink has to write to the database

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#182]
[k8s.io/apimachinery/pkg/apis/meta/v1/unstructured](k8s.io/apimachinery/pkg/apis/meta/v1/unstructured) provides the `Unstructured` type to handle Kubernetes objects that are part of the meta v1 schema without needing to know the kind in advance. I'm pretty sure this encompasses all of the resources that KubeArchive will watch. `Unstructured` can provide the ability to look up all of the data we need to from the Kubernetes object:
* api version
* deleted timestamp (when the cluster deleted the object
* kind
* name
* namespace
* resource version
* uid of the object

The only data `Unstructured` doesn't provide, that we still need, are values that cannot be obtain from the kubernetes api (cluster name and cluster uuid)

We should use this instead of `models.ResourceEntry` and Database.WriteResource should accept this type as a parameter

Outcome:
* the `database.WriteResource` command uses `Unstructured` instead of `models.ResourceEntry`
* validation logic for incoming cloudevents is moved out of the model package
* models.ResourceEntry is removed

Edit: Expand scope of this issue to include replacing `models.Resource` with `unstructured.Unstructured` as well

**Comment by maruiz93** [comment]
Interesting! Given what you said, I think that `Unstructured` can also replace `models.Resource` used by the API Server (in fact, I think that it makes  sense that sink and rest api use the same model to represent the resource stored in the database) what do you think?

**Comment by ggallen** [comment]
We don't need `cluster_name` and `cluster_uuid`.  I thought we agreed to get rid of them.

And @maruiz93, you are absolutely right. We should use the same thing everywhere.

**Comment by skoved** [comment]
> We don't need `cluster_name` and `cluster_uuid`. I thought we agreed to get rid of them.

If we did (I don't remember the outcome of the discussion about it) that schema change has not been merged yet and I think that it should be handled separately from this change

> Interesting! Given what you said, I think that `Unstructured` can also replace `models.Resource` used by the API Server (in fact, I think that it makes sense that sink and rest api use the same model to represent the resource stored in the database) what do you think?

I agree. That was part of the motivation behind this change. I could expand the scope of this issue to make `unstructured.Unstructured` replace `models.Resource` as well

**Comment by ggallen** [comment]
I created https://github.com/kubearchive/kubearchive/issues/183 for the removal of `cluster_name` and `cluster_uuid`.  I just didn't want you to include them in this change since they are going away.
