### ISSUE TITLE
Deploy a logging solution for development

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#189]
There is interest in us returning additional data related with Kubernetes resouces, mainly logs. We need to deploy a logging solution in development so we can start implement a system to reach to those systems.

**Comment by rh-hemartin** [comment]
I assigned to @maruiz93 that showed interest in doing this.

**Comment by maruiz93** [comment]
Already addressed in https://github.com/kubearchive/kubearchive/issues/408
