### ISSUE TITLE
Cache the requests of kubernetes resources in REST API Server

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#195]
Recently a new middleware layer was included in the API Server to query the resources from k8s API and be able to get the kind of a resource given the pluralized name, the group and the version.

K8s go client include a [CachedDiscoveryClient](https://pkg.go.dev/k8s.io/client-go/discovery/cached/disk#NewCachedDiscoveryClientForConfi) that we should use instead of the current one to reduce the ammount of queries done to the kubernetes API

**Comment by rh-hemartin** [comment]
I would like to see proof of this, do you have any idea how to measure this?

**Comment by maruiz93** [comment]
EDIT: I posted the disk cached but I would like to try first the mem cache client, [this one](https://github.com/kubernetes/client-go/blob/master/discovery/cached/memory/memcache.go)

What do you mean about proof? 

To expand a little more this topic, IIUC, that objet would keep in memory a map with the same information returned by the K8S API when we do `kubectl api-resources`.

That information is very unlikely to change, so if this is stored in memory, it should potentially not be refreshed in a long time. If it does not found the groupversion being asked, then a request is done to kubernetes (and maybe retried depending on the error received)

**Comment by maruiz93** [comment]
Maybe you were referring to track performance of the k8s API? Something like [this](https://www.redhat.com/en/blog/kubernetes-api-performance-metrics-examples-and-best-practices)?

**Comment by rh-hemartin** [comment]
By proof I meant that we have a way in which we can compare how its calling less the Kubernetes API. My first guess is to compare the logs of the K8s API before and after the change, given that these requests can be seen in that log.

**Comment by rh-hemartin** [comment]
> Maybe you were referring to track performance of the k8s API? Something like [this](https://www.redhat.com/en/blog/kubernetes-api-performance-metrics-examples-and-best-practices)?

Nothing that complex, just looking at logs or something similar.

**Comment by maruiz93** [comment]
We don't have logs for the http client embedded in the k8s client that we are using for the kubearchive rest api server.

I've created https://github.com/kubearchive/kubearchive/issues/202 to address that

**Comment by rh-hemartin** [comment]
Ah, didn't think of that but sounds good to be able to follow traces to services we call.
