### ISSUE TITLE
Enable traces for knative eventing on development

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#199]
We should enable traces for Knative Eventing on the development environment so our sink also provides traces. If the ApiServerSource is not enabled for tracing our sink does not send traces (due to a mechanism to avoid broken traces where some spans are reported and some are not).

This leads me to some questions:

* should we force traces on our end?
* what happens if they enable tracing? do we enable it as well?
* should we care about if they trace or not?

**Comment by skoved** [comment]
I think we probably need to make it so that traces from from KubeArchive can be created without having to depend on tracing being enabled in Knative Eventing

**Comment by rh-hemartin** [comment]
> I think we probably need to make it so that traces from from KubeArchive can be created without having to depend on tracing being enabled in Knative Eventing

I agree... but I also have the feeling that we need to be in sync with Knative Eventing.

What about having three modes for telemetry? Disabled, enabled and delegated. Delegated would be the behaviour that we saw, enabled would be ignoring the traceparent sampled flag.

**Comment by rh-hemartin** [comment]
Closed in favor of #294 and #295
