### ISSUE TITLE
Set service.name for OpenTelemetry spans

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#207]
Currently we are sending telemetry spans with an empty service name from both the KubeArchive sink and API, we need to add its name. Probably `kubearchive.<component>` is the right move for the name, so `kubearchive.sink` and `kubearchive.api`, and eventually `kubearchive.operator`.

**Notes**

* The `kubearchive.api` string we are sending to the otelgin library its not setting the service name.

**Comment by skoved** [comment]
I agree on that naming convention. The otel configuration that is being used looks for an env var `OTEL_SERVICE_NAME` and sets the service name to the value of the env var. The easy way to add this would be to add [after this line](https://github.com/kubearchive/kubearchive/blob/main/charts/kubearchive/templates/_helpers.tpl#L13) to the `kubearchive.v1.otel.env` template. `kubearchive.<component>` can be created with `{{ $.Release.name }}.{{ .name }}`
