### ISSUE TITLE
Support global configuration of filters.

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#223]
KubeArchive needs to support the setting of "global" filters. This will allow an administrator to force some resources to be always archived in every namespace where `KubeArchive` is enabled.

This is related to https://github.com/kubearchive/kubearchive/issues/221.

**Comment by ggallen** [comment]
@skoved, as we talked about, I don't believe there is any work for the operator here.

To support global archive and delete configuration, a k9e admin should just be able to add the global configuration to the `ConfigMap` manually, using some pre-defined global namespace name like `_global`.  This namespace name should be valid YAML but an invalid namespace name to avoid potential clashes.

I'm going to label this for the sink.

**Comment by skoved** [comment]
support for global filters on the sink side was included in #286, but I forgot to link this issue to that PR
