### ISSUE TITLE
Add pagination to the KubeArchive API Server responses

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#226]
It could be a large amount of resources stored in KubeArchive database.

We should include a default limit of resources to response by default and a way to paginate the full response.

K8s API uses the parameters `limit` and `continue` for that. The goal is to mimic that functionality.

More information in https://github.com/kubernetes/kubernetes/issues/49338

**Comment by rh-hemartin** [comment]
See also the rendered docs: https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks
