### ISSUE TITLE
Sink should not try to delete a resource from a DELETE cloudevent

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#232]
after the sink deletes a resource, it receives a delete event for that same resource from ApiServerSource. This event needs to be processed to obtain the timestamp for when that resource was deleted. However, the sink needs to skip trying to delete the resource in this case

**Acceptance Criteria**:

- the sink processes delete events
- the sink does not try to delete already deleted resources

**Comment by ggallen** [comment]
I don't think the sink should ever receive a DELETE cloudevent, which would solve this problem.

**Comment by rh-hemartin** [comment]
> I don't think the sink should ever receive a DELETE cloudevent, which would solve this problem.
> 
> In other words, shouldn't we just configure `ApiServerSource` not to send a cloudevent on a DELETE?

As long as we have `cluster_deleted_ts` in the schema we need to receive the delete messages to populate it. But we can drop it if it does not serve any use-case, or a use-case that can replace `cluster_deleted_ts` to work.

**Comment by ggallen** [comment]
> As long as we have cluster_deleted_ts in the schema we need to receive the delete messages to populate it.

No we don't. When the `when-delete` expression is true, and we submit the delete command, we can fill in the request.

**Comment by skoved** [comment]
> No we don't. When the when-delete expression is true, and we submit the delete command, we can fill in the request

That happens after the sink has written the k8s object to the database. The flow is:

1. receive cloudevent
2. validate the payload is a k8s object
3. write the object to the database
4. check if the object needs to be deleted and delete it if it passes the check

**Comment by ggallen** [comment]
But you can easily do this:

1. receive cloudevent
2. validate the payload is a k8s object
3. write the object to the database
4. check if the object needs to be deleted and delete it if it passes the check
5. if the delete request succeeds, update the deleted timestamp

I see no reason to depend on the delete event. The way you have it set up now, you are sending *two* delete events, neither of which are really needed.  And you have to special-case to ignore one of the completely.

**Comment by skoved** [comment]
after discussion today, I will go with the following solution

1. receive cloudevent
2. validate the payload
3. check if the object needs to be deleted and delete if it passes the check
4. add deletion timestamp to the k8s object after receiving 200 response from kubernetes api
5. write object to the database

**Comment by skoved** [comment]
additionally, the ApiServerSource configuration will be updated so that it will not create cloudevents with the type `*.delete`

**Comment by ggallen** [comment]
> after discussion today, I will go with the following solution
> 
> 1. receive cloudevent
> 2. validate the payload
> 3. check if the object needs to be deleted and delete if it passes the check
> 4. add deletion timestamp to the k8s object after receiving 200 response from kubernetes api
> 5. write object to the database

I don't think the resource should be deleted until the resource is written successfully to the database.

**Comment by skoved** [comment]
> > after discussion today, I will go with the following solution
> > 
> > 1. receive cloudevent
> > 2. validate the payload
> > 3. check if the object needs to be deleted and delete if it passes the check
> > 4. add deletion timestamp to the k8s object after receiving 200 response from kubernetes api
> > 5. write object to the database
> 
> I don't think the resource should be deleted until the resource is written successfully to the database.

you're right, I overlooked that. Then I think my point about this stands and I'm going to reopen my previous PR

**Comment by ggallen** [comment]
> you're right, I overlooked that. Then I think my point about this stands and I'm going to reopen my previous PR

What point is that?

**Comment by skoved** [comment]
ignore my last message. I'm not sure what I was talking about. I'm using the flow that you mentioned previously

>     1. receive cloudevent
> 
>     2. validate the payload is a k8s object
> 
>     3. write the object to the database
> 
>     4. check if the object needs to be deleted and delete it if it passes the check
> 
>     5. if the delete request succeeds, update the deleted timestamp

I'm also making a change the to ApiServerSource that we use so that it doesn't send delete messages. This will require us to use knative-eventing v1.15.0 (bump from v1.14.3 which we currently use). We're already using v0.42.0 of the knative-eventing go library so we don't need to make any changes there.
