### ISSUE TITLE
Add database initialization to hack/quick-install.sh

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#234]
Currently after we run `hack/quick-install.sh` we need to initialize the database. This step is always the same and should be easy to automate.

**Acceptance Criteria**

* Have the initialization of the database included in the `hac/quick-install`.
* Port-forwarding should be canceled after the initialization completes, we don't want uncontrolled processes.

**Comment by maruiz93** [comment]
I think that if we address the linked issue, this issue will be automatically done

**Comment by rh-hemartin** [comment]
> I think that if we address the linked issue, this issue will be automatically done

Yes this issue will be solved then, however I find it more difficult than incorporating the following code into the script:

```
kubectl port-forward -n kubearchive svc/kubearchive-database 5432:5432 &
FORWARD_PID=$!
go run database/init_db.go
kill ${FORWARD_PID}
```

However if the linked issue is resolved before, this will be closed.

**Comment by maruiz93** [comment]
Should we consider the linked issue a blocker and this issue a proposed workaround?

**Comment by rh-hemartin** [comment]
> Should we consider the linked issue a blocker and this issue a proposed workaround?

No, this is not blocked by the other issue. Also, this being a workaround is highly subjective. I had to consider something a workaround I would consider the process in itself a workaround, not the act of automating it.

**Comment by mafh314** [comment]
Is this covered by https://github.com/kubearchive/kubearchive/pull/346?

**Comment by maruiz93** [comment]
I think that `hack/install-database.sh` covers this issue, doesn't it @rh-hemartin ?

**Comment by rh-hemartin** [comment]
Si, this is covered now.
