### ISSUE TITLE
Sink should batch writes to the database

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#239]
Individual transactions for writes to the database, the sink should batch its writes to be more efficient.

Some decisions need to be made:

- how big should a batch be
- howl long should a batch wait before writing anyway

**Comment by rh-hemartin** [comment]
We talked about dropping this until we see there are problems with writes to the database, as it would introduce complexity. Feel free to close it, we can reopen or create a new one in the future.

**Comment by maruiz93** [comment]
As a side note, when we want to include batching, we can continue with `database/sql` package to do it (see [example](https://stackoverflow.com/questions/12486436/how-do-i-batch-sql-statements-with-package-database-sql)) but we might want to consider changing to `gorm` (docs about batching [here](https://gorm.io/docs/create.html#Batch-Insert))

**Comment by skoved** [comment]
Closing for now since it's not an issue currently. We can reopen in the future if we need to improve performance around writing to the database
