### ISSUE TITLE
Add retries to Database connection

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#241]
The sink and api server share code for connecting to the database. Instead of failing immediately, the connection attempt should be retried a few times if the first attempt fails. We could use one of these libraries for retries:

- https://github.com/avast/retry-go
- https://github.com/giantswarm/retry-go
- https://github.com/sethgrid/pester
- https://github.com/cenkalti/backoff
- https://github.com/rafaeljesus/retry-go
- https://github.com/matryer/try

Since it some times takes a little bit for the database to become ready during development deployments, we should add a delay between retries

**Comment by rh-hemartin** [comment]
I think the avast one looks small, has the features we need and its simple to understand from reading the code. Also we can copy it over in case we need to update it. Others that are even smaller and easier to understand do not have exponential backoff, which should be the standard waiting mechanism.

**Comment by mafh314** [comment]
The issue [#242]( https://github.com/kubearchive/kubearchive/issues/242) is already merged. The library selected to add retries was https://github.com/avast/retry-go based on the comments added here.
