### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#252]
We need to start thinking about installation for production. We need some starting documentation so people interested can install it and configure it to a bare minimum.

**Comment by maruiz93** [comment]
I would say that the main differences between development and production is:
* The user can provide its own database (configurable in the helm chart values)
* We need to provide a way of deploying the schema in this DB, my first approach would be a k8s Job deployed with helm that runs the init_db.go script

**Comment by ggallen** [comment]
> * The user can provide its own database (configurable in the helm chart values)

This should say the user MUST supply their own database.

> * We need to provide a way of deploying the schema in this DB, my first approach would be a k8s Job deployed with helm that runs the init_db.go script

I don't agree.  We can simple provide the Postgres SQL file to create the database, and then let the user do it. This is outside of the scope of `KubeArchive`.

I need to take a look at how we are doing database stuff.

**Comment by rh-hemartin** [comment]
As per the discussion on #258 we need to require the user for a dedicated database for KubeArchive.

**Comment by maruiz93** [comment]
As a starting point, giving the `.sql` file is a good idea, I wan't to extract the sql file from `init_db.go` that we have right now. I think that would be work related to https://github.com/kubearchive/kubearchive/issues/85 (see last comment)

But, I think that for the user perspective, the final process should be something like:

1. Install requirements in cluster (cert-manager and knative-eventing if I don't have them yet)
2. Run helm chart with the values that I need

@ggallen you are proposing to do:

1. Install requirements in cluster
2. Run SQL on my DB
3. Run helm chart with the values that I need

right?

I think that we could potentially merge step 2 and 3

**Comment by ggallen** [comment]
@maruiz93 , I am proposing:

1. Install requirements in cluster (database is a requirement)
2. Apply `KubeArchive` YAML file.

That may be too simple, but I don't want helm necessarily.

> I wan't to extract the sql file from init_db.go that we have right now.

Something seems off here, and this seems backwards to me.  I'll have to look at this.

But I think the correct way to do this is to create the database as we want it is Postgres, then dump it using `pg_dump` with whatever options make sense. Then this file can be used to create and initialize the dtabase.

**Comment by maruiz93** [comment]
> Install requirements in cluster (database is a requirement)

The database doesn't need to be located in the cluster, it can be outside of it, that's why I didn't stated as a step, I'm considering that the user already have a postgresql database new or with other stuff before installing kubearchive.

And that leads me to the second step:

> Apply KubeArchive YAML file.

This YAML file should contain the URL and credentials of the database. As the user should provide their own database with its credentials, if they need to manually update the YAML file of the sink deployment and the api server deployment to provide the URL and the credentials things will get really messy, that's why I'm sticking to helm

**Comment by ggallen** [comment]
> This YAML file should contain the URL and credentials of the database. As the user should provide their own database with its credentials, 

No. I think both of those deployments should in fact pull the URL and database information from one or more `ConfigMaps` (and maybe `Secrets`).

**Comment by maruiz93** [comment]
That will mean the following for the user:

[Once the user have its PostgreSQL server]

1. Run the SQL script in the database to set the schema
2. Modify part of the YAMLs of KubeArchive to introduce at least the DB URL in a ConfigMap
3. Apply the KubeArchive YAML

We are still doing manual modifications in kubernetes resources yaml that would be easier with helm templating (and we already have it)

**Comment by rh-hemartin** [comment]
We agreed to use a single YAML for release. This ticket needs to wait for that to be done in order to publish a meaningful piece of documentation. See #277 for information about the release YAML.
