### ISSUE TITLE
Don't initialize "public.resource", use "resource" instead

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#258]
The KubeArchive init process creates the table "public.resource". "public" is the default namespace, but database admins may want to restrict user access to a certain namespace. To allow administrators to manage better the kubearchive user permissions, KubeArchive needs to drop the "public". This change will make KubeArchive compatible with PostgreSQL schemas if they administrators want to.

PostgreSQL schemas: https://www.postgresql.org/docs/current/ddl-schemas.html

**Edit**: changed the approach to drop "public" first.

**Comment by maruiz93** [comment]
I think that we should create a `kubearchive` database with the `CREATE DATABASE` SQL [instruction](https://www.postgresql.org/docs/current/sql-createdatabase.html) and then include the table inside it.

**Comment by ggallen** [comment]
> I think that we should create a `kubearchive` database with the `CREATE DATABASE` SQL [instruction](https://www.postgresql.org/docs/current/sql-createdatabase.html) and then include the table inside it.

Agreed. We're not doing that?  We should have our own database called `kubearchive`.  And our database should not be shared with anyone.

The server itself could be shared, but not the database.

**Comment by rh-hemartin** [comment]
> We're not doing that? 

No, we are running in whatever database the user provides us.

> I think that we should create a kubearchive database with the CREATE DATABASE SQL instruction and then include the table inside it.

We may not have permissions to setup a database with the account the user provides to us.

> We should have our own database called kubearchive. And our database should not be shared with anyone.

I agree that having isolation would be nice, as its fewer options for something to go wrong. The user providing a database for us its probably the most common scenario. 

From this I get that we need to inform the user that we require our own database within the PostgreSQL instance. However we don't have any reasons for that and I think that database. I added a comment on another ticket related with that.

Anything related with the "public" part of this issue?

**Comment by maruiz93** [comment]
> We may not have permissions to setup a database with the account the user provides to us.

You're right, this part should be done only for the development part as we create the db from scratch, but the user should provide the db with whatever schema they want us to use for kubearchive, so I agree with your latest comment.

I agree that we should drop the `public` part of the create table instruction

**Comment by ggallen** [comment]
> > We're not doing that?
> 
> No, we are running in whatever database the user provides us.

I've misunderstood what we are doing, and we should not be doing this.

The user should provide use with a database server, and we should provide them with the SQL to create the `kubearchive` database. This SQL should also create a `kubearchive` user that has appropriate permissions to read/write to whatever tables it need. And then `KubeArchive` should connect using this user.

**Comment by maruiz93** [comment]
@ggallen what you suggest only makes sense IF we agree on delegating to the user executing the SQL (that is a decission that needs to be made yet) otherwise, if setting the schema in the database is going to be part of the installation process, we may face the problem that hector stated previously of not having enough credentials to create the database in the postgresql server

**Comment by ggallen** [comment]
> what you suggest only makes sense IF we agree on delegating to the user executing the SQL

I didn't think there was any debate over this.  We are not database administrators, and `KubeArchive` should never have nor request those permissions. Database creation is an administrator function. We provide the SQL as part of the installation process, and then an administrator applies that SQL to create the database and `kubearchive` user on their database server. The `kubearchive` user should be the owner of the database.

Then `KubeArchive` accesses the database using that `kubearchive` database user.

**Comment by maruiz93** [comment]
Something I was messing with is that I was considering `DATABASE` and `SCHEMA` synonims (they are in DBs like MySQL but not in PostgreSQL, see [docs](https://www.sprinkledata.com/blogs/postgresql-schema-vs-database-unveiling-the-distinctions-for-effective-data-management#:~:text=PostgreSQL%20Schema%20vs.-,Database%3A%20Key%20Differences,and%20RENAME%20to%20modify%20data.)
