### ISSUE TITLE
Create database schema SQL file for release and other changes

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#271]
The database should be creating using an SQL file that a user can simply run using `psql`. This SQL script should do the following:

1. Create the `kubearchive` database.
2. Create all the tables, indexes and any other constraints in the `kubearchive` database.
3. Create a `kubearchive` user who is the owner of the `kubearchive` database. This user should be used for all KubeArchive database connections.
4. Set the password for the `kubearchive` user to some default value. This value will be recommended to be changed by the user as installation time.

The best way to create this script is to create the database as desired, then dump it using the `pg_dump` utility. This also sets a number of other options on the database by default.  

When changes are needed in the future, simply use `psql` to create the database using the SQL script. Then make the changes to the database. Next, use `pg_dump` to generate a new SQL script. Finally, compare this new script to the committed version, and if the changes are as expected, commit it.

Part of this work should also extract the default password and create a secret for it in the `kubearchive` namespace. This secret should be mounted by whatever processes need to access the database (sink, etc). At KubeArchive installation time, the user should provide the password for the `kubearchive` database user so the installation process can create the needed secret correctly.

Additionally, the database connection information (URL, username, etc) should be stored in a `ConfigMap` and read by database users such as the sink.

**Comment by maruiz93** [comment]
In PostgreSQL there is also the `schema` (different concept from `database`, a `database` can allocate several schemas, more information [here](https://www.sprinkledata.com/blogs/postgresql-schema-vs-database-unveiling-the-distinctions-for-effective-data-management#:~:text=PostgreSQL%20Schema%20vs.-,Database%3A%20Key%20Differences,and%20RENAME%20to%20modify%20data.)).

 I included  a `kubearchive` schema in the PR https://github.com/kubearchive/kubearchive/pull/269/files based on the issue https://github.com/kubearchive/kubearchive/issues/258.
 
 You didn't mention the `schema` but are you ok with creating both database AND schema?

**Comment by skoved** [comment]
> Additionally, the database connection information (URL, username, etc) should be stored in a ConfigMap and read by database users such as the sink.

Right now, the helm chart creates the username, url, and password as a secret and the sink and api server use those secrets to create environment variables
