### ISSUE TITLE
Use a kubernetes go client instead of running external CLIs with `os/exec` package

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#275]
In the integration tests we currently use `os/exec` go package to run `ko` and `kubectl` CLIs to interact with Kubernetes.

Kubernetes provides several go clients for kubernetes under the [client-go](https://github.com/kubernetes/client-go) library.

We use different clients for different things in the operator, API server and sink. 

See if there is a chance to prevent running a CLI and use the go clients to interact with kubernetes.

**Comment by rh-hemartin** [comment]
Over time we changed the approach organically and we don't use os.exec anymore on the integration tests.
