### ISSUE TITLE
Opentelemetry should be enable/disabled globally

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#276]
Right now, each component needs to set `<component>.observability` so that otel can be enabled in the component. This boolean should be configured globally and then set the appropriate env vars in each component.

values.yaml would have something like `kubearchive.observability` instead. This will require a slight change to the sink and api server deployments

**Acceptance Criteria**:

- add `kubearchive.observability` to values.yaml the default value should be `false`
- remove `sink.observability` and `apiServer.observability` from values.yaml
- change [this line](https://github.com/kubearchive/kubearchive/blob/main/charts/kubearchive/templates/api_server/api_server.yaml#L51) in the api server deployment to `{{ include "kubearchive.v1.otel.env" .Values.kubearchive | indent 12 }}` 
- change [this line](https://github.com/kubearchive/kubearchive/blob/main/charts/kubearchive/templates/sink/sink.yaml) in the sink deployment to `{{ include "kubearchive.v1.otel.env" .Values.kubearchive | indent 12 }}`

**Comment by ggallen** [comment]
I will try to do this as part of https://github.com/kubearchive/kubearchive/issues/236, which I am going to tackle next.

**Comment by rh-hemartin** [comment]
This is already being done in #214 , you both already reviewed it and it include similar changes.

**Comment by ggallen** [comment]
Handled in https://github.com/kubearchive/kubearchive/pull/214.

**Comment by skoved** [comment]
oops :upside_down_face:
