### ISSUE TITLE
Any guarantees resources are not missed?

### ISSUE THREAD

**Issue by lcarva** [kubearchive/kubearchive#368]
Consider the case where the kubearchive controller is busy, and a certain resource is created and deleted before kubearchive has a chance to process it. Does kubearchive provide any guarantees that such resource will be archived anyways? (Assuming, of course, the resource matches the expression from the configuration.)

**Comment by skoved** [comment]
KubeArchive receives updates about if a resource is created/updated as a CloudEvent from [Knative-Eventing's ApiServerSource](https://knative.dev/docs/eventing/sources/apiserversource/). The CloudEvent contains the full resource in the payload, so even if KubeArchive cannot process the event immediately (maybe it is busy processing earlier messages), data does not get lost. KubeArchive does not directly depend the resource's state in the cluster at the time an event is processed.

**Comment by lcarva** [comment]
Great. Thanks!
