### ISSUE TITLE
Document delay from KubeArchiveConfig to sink updating

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#372]
I see a ~1 minute delay between creating/deleting/updating a KubeArchiveConfig and the sink getting the update. Anyone can confirm this? Just deploy KubeArchive from main, open two terminals: one `logs -f` on the sink an the other modifying the KubeArchiveConfig on `test`. We should document this behaviour.

**Acceptance Criteria**

* Document that changes in KubeArchiveConfig take ~1 minute to apply.

Edit: change this issue to be a documentation issue.

**Comment by rh-hemartin** [comment]
I read the ConfigMap documentation and this delay its expected: https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

> When a ConfigMap currently consumed in a volume is updated, projected keys are eventually updated as well. The kubelet checks whether the mounted ConfigMap is fresh on every periodic sync. However, the kubelet uses its local cache for getting the current value of the ConfigMap. The type of the cache is configurable using the configMapAndSecretChangeDetectionStrategy field in the [KubeletConfiguration struct](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/). A ConfigMap can be either propagated by watch (default), ttl-based, or by redirecting all requests directly to the API server. As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the Pod can be as long as the kubelet sync period + cache propagation delay, where the cache propagation delay depends on the chosen cache type (it equals to watch propagation delay, ttl of cache, or zero correspondingly).

**Comment by maruiz93** [comment]
I think that we can reopen this issue to add this information to our docs.

BTW, I have seen that by default `configMapAndSecretChangeDetectionStrategy` is set to `Watch` so that  means there is no cache in place.

I found [this post](https://ahmet.im/blog/kubernetes-secret-volumes-delay/) where it's really well explain how the whole syncronization thing works in this case and also, that there is a way to enforce a quicker update (that we could potentially add in the operator).

IIUC, if after the operator sets the changes in the configmap, updates something in the pod (e.g. an annotation), the pod will be reconciled faster.

**Comment by skoved** [comment]
the operator could update an annotation that has an easy value to get, like the current time after the ConfigMap is updated

**Comment by rh-hemartin** [comment]
From these suggestions I understand that the intention was that the updates were instantaneous? If so, open a new issue and we can discuss there about how to solve it.

**Comment by ggallen** [comment]
Why do we want or expect these updates to be instantaneous?  It looks like we are complicating things here for no good reason.

**Comment by rh-hemartin** [comment]
> Why do we want or expect these updates to be instantaneous? It looks like we are complicating things here for no good reason.

I agree. Let's document it so the user are aware that it takes a while to sync, and that's it.

**Comment by maruiz93** [comment]
I just wanted to mention that *if* in the future we want to update the behavior to be in less time there is already a way for doing it, in other words, there is not a technical limitation.
I'm ok with just documenting it for now.

**Comment by rh-hemartin** [comment]
This is not happening anymore, as now the filters update using a watcher which is pretty fast.
