### ISSUE TITLE
Introduce integration test that generates traffic

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#377]
I think its time we add a test that generates traffic, makes the sink save some stuff in the database and then queries the API for the resources. My idea is that we create a test namespace, create a KAC that will archive and delete Pods and Jobs, inspect the logs from the sink to check that the filters have been updated, then create a Pod and  a Job and then query the API to check those are returned. Also check that the Job and Pod were deleted from the cluster.

**Comment by ggallen** [comment]
I think we can use the log generators for this.
