### ISSUE TITLE
Database secret in the installation process

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#380]
Currently we ask the user to apply our YAML to install and then to patch the secret we add. This was documented in #378 . There were some comments proposing changes to the flow. If I understood correctly, the proposed flow is:

* Have default values on the database secret in the release YAML.
* Have the user download the release YAML, edit it and then apply it.

This looks simpler than patching and avoids the `kubectl rollout restart` after installing.

**Comment by rh-hemartin** [comment]
There are some discussions about being agnostic of the database being used. That work is more than it sounds, as we would need to include more drivers, adapt calls, etc. I'm not sure its worth it.

**Comment by ggallen** [comment]
My suggestion is simple. Just put all our development values in the secret YAML file.

1. Developers don't have to change anything, they just apply it.
2. Production are suggested to change it, so the instructions are the same.
