### ISSUE TITLE
Unify the deployment of the database for testing and development purposes

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#390]
## Context

KubeArchive in meant to be used along a Postgres Database provided by the user.

For development and testing purposes we deploy our own database.

### Development

We provide the option `database.enabled` in KubeArchive's Helm chart to deploy a database along the other components of KubeArchive.

The database resources are in [charts/kubearchive/templates/database](https://github.com/kubearchive/kubearchive/tree/main/charts/kubearchive/templates/database)

### Testing

For the [integration tests](https://github.com/kubearchive/kubearchive/blob/main/.github/workflows/go_test_integration.yml) we use the [hack/quick-install.sh script](https://github.com/kubearchive/kubearchive/blob/main/hack/quick-install.sh) that deploys a Database and configure it in the way that we expect the user to do:
1. Create a kubearchive user
2. Create a kubearchive database
3. Apply the DDL of the release

## Problem

The code for both deployments is really similar and the aim of this issue is to unify them to prevent duplication and keep things short while keeping the integration test steps as similar as we could to the steps that will be reproduced by a Production user.

## Proposal

* Adjust the Helm Chart DB template with the following:
  * Create a specific namespace for the database
  * Create a ConfigMap with the contents of `ddl-resource.sql`
  * Move the database to its own namespace
  * Deploy the database with credentials different from the ones that kubearchive will use (e.g, `postgres` or `root`)
  * Mount the ConfigMap with the `ddl-resource.sql` in the Deployment, in different locations (to be automatically executed or not) based on the chart value `global.production`
* In `hack/quick-install.sh` replace the call of `hack/database-install.sh` for the following:

  ```bash
  kubectl apply -f - <<< $(helm template kubearchive charts/kubearchive \
    -s templates/database/database.yaml \
    --set "database.enabled=true"  --set "global.production=true")

  kubectl rollout status deployment --namespace=databases --timeout=30s
  sleep 15  # Wait for PostgreSQL to be really ready

  echo "CREATE USER kubearchive WITH ENCRYPTED PASSWORD 'P0stgr3sdbP@ssword';" | kubectl exec -i -n databases deploy/kubearchive-database -- psql -h localhost
  echo "CREATE DATABASE kubearchive WITH OWNER kubearchive;" | kubectl exec -i -n databases deploy/kubearchive-database -- psql -h localhost
  kubectl exec -i -n databases deploy/kubearchive-database -- psql -h localhost --user=kubearchive kubearchive -f /ddl.sql
  ```

* Remove `hack/database-install.sh` file as the functionality is replaced

### Other tweaks that could be also addressed in this or in other issues to improve the workflow:

* Move the creation of the user and database to the DDL (addressed in https://github.com/kubearchive/kubearchive/issues/381)
* Add a readiness probe on the DB deployment to remove the `sleep`

**Comment by ggallen** [comment]
This seems overly complicated to me.

**Comment by maruiz93** [comment]
> This seems overly complicated to me.

I think that maybe seeing the proposal in bullet points instead of the PR gives that impression... I will create a quick PR with the changes.

**Comment by maruiz93** [comment]
@ggallen I created the PR https://github.com/kubearchive/kubearchive/pull/394 to show my proposal in case you want to check it out.

**Comment by rh-hemartin** [comment]
I don't think its that bad that we have duplicated code related to the database in testing and development. Given that we have two distinct processes to deploy, its normal that there are pieces of code that repeat. However if we really need to deduplicate code I feel it would be easier to go the other direction. Did you try to delete the database from Helm and introduce `bash hack/install-database.sh` in the development process?

**Comment by maruiz93** [comment]
> Did you try to delete the database from Helm and introduce bash hack/install-database.sh in the development process?

I thought about it, but in the `hack/quick-install.sh` we have [this line](https://github.com/kubearchive/kubearchive/blob/main/hack/quick-install.sh#L33-L38):

```bash
helm template kubearchive charts/kubearchive -n kubearchive \
    --include-crds \
    --set "global.production=true" \
    --set "database.enabled=false" > /tmp/kubearchive-not-resolved.yaml
ko resolve -f /tmp/kubearchive-not-resolved.yaml --base-import-paths > /tmp/kubearchive.yaml
kubectl apply -n kubearchive -f /tmp/kubearchive.yaml
```

And that made me think that it makes sense to have a similar line in the script for deploying the database, taking advantage of what we have in the helm chart and deploy it like this:

```bash
kubectl apply -f - <<< $(helm template kubearchive charts/kubearchive \
  -s templates/database/database.yaml \
  --set "database.enabled=true"  --set "global.production=true")
```

which is essentially the same as:
```bash
helm template kubearchive charts/kubearchive -n kubearchive \
    -s templates/database/database.yaml \
    --set "global.production=true" \
    --set "database.enabled=true" > /tmp/database.yaml
kubectl apply -n kubearchive -f /tmp/database.yaml    
```

Also, even though running the line `hack/install-database.sh` is not a big deal at all, I don't see how this is better than the other.

**Comment by rh-hemartin** [comment]
>  I don't see how having to run that extra line for development is better than not having to do it.

I think that having to run that extra line for development makes it better as it becomes more similar to the production deployment.
