### ISSUE TITLE
Create indexes in the database

### ISSUE THREAD

**Issue by mafh314** [kubearchive/kubearchive#441]
Create indexes in the database for the following fields:
- api_version
- kind
- name
- namespace
And also update this https://kubearchive.github.io/kubearchive/main/reference/database.html
https://github.com/kubearchive#database-model

**Comment by ggallen** [comment]
I don't think we want indexes on all these fields individually.  It may make sense to only have an index on `namespace`.

Or potentially `(namespace, kind, api_version)`.  I"m not sure `name` makes sense for an index.

I don't believe we'll have any queries that span multiple namespaces.

**Comment by maruiz93** [comment]
As a remainder of what we currently have (and immediately working on):

* Queries with  `kind` and `api_version` in the `WHERE` clause
* Queries with `kind`, `api_version` and `namespace`
* Queries with `kind`, `api_version` and `name` (in progress)
* Queries with `kind, `api_version`, `namespace` and `name`  (in progress)

And we will probably want to add soon ordering based on deletion time for every query

I think we will probably have more "namespaced" queries, so, my first approach would be to try a multicolumn index with the following order: `kind`, `api_version`, `namespace`, `name` and maybe we could potentially also add a second multicolumn index with: `kind`, `api_version`, `namespace` and the deletion time.

I ran into [this video](https://www.youtube.com/watch?v=HubezKbFL7E&list=PLfkvOiuhoOfVRU-4Uoh9u1zHpluAXa3_k&index=7) that does a REALLY good explanation of common pitfalls on index usage by developers and I think recommend taking a look at it.

**Comment by ggallen** [comment]
Why would we ever want non-namespaced queries?  Can you even do that for namespaced objects?

If I remember correctly, we aren't supporting archiving cluster-level resources.

**Comment by ggallen** [comment]
> the following order: `kind`, `api_version`, `namespace`, `name`

Why would you ever want to include `name` here? Name is unique to the other three, so I don't think there's any advantage to including it.

**Comment by maruiz93** [comment]
> If I remember correctly, we aren't supporting archiving cluster-level resources. Is it to support --all-namespaces?

Yes, it is. 

> Why would you ever want to include name here? Name is unique to the other three, so I don't think there's any advantage to including it.

The advantage is to find it faster. Say that you have a largs number of pods in a particular namespace but you a querying a particular one by name through the endpoint `/api/v1/namespace/<my_ns>/<my_pod>` then having that field inside the index could be pretty useful

**Comment by ggallen** [comment]
How is it going to find it faster?  Indexes "group" things together to make searching easier. By the time you have grouped and found the records for `namespace`, `kind`, and `api_version`, there's only one `name`.

**Comment by ggallen** [comment]
If indexes provide sorting as well, which I think they do, then this is probably a good idea. I didn't realize that.

**Comment by mafh314** [comment]
> If indexes provide sorting as well, which I think they do, then this is probably a good idea. I didn't realize that.
  In Postgresql, only the B-tree index provides sorting.
  https://www.postgresql.org/docs/current/indexes-ordering.html
