### ISSUE TITLE
Sink doesn't react to filters updating

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#467]
If you update the filters in a KubeArchiveConfig that already exists, the sink will not react to the update and will continue to use the old filters. The sink should be able to update the filters when the ConfigMap is updated to include the updated filters.

The work around for updating the KubeArchiveConfig is to delete the KubeArchiveConfig and create a new one with the desired filters

**Comment by skoved** [comment]
This happens because the files created in from the mounted ConfigMap are symlinks, so the underlying file does not update, but the file that the symlinks are pointing to

**Comment by rh-hemartin** [comment]
Keep in mind that if this gets too complex maybe its better to receive the filters with a POST request from the operator.
