### ISSUE TITLE
`hack/quick-install.sh` fails when trying to create postgres database

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#485]
when I run `hack/quick-install.sh` it fails with the following error

```
error: unrecognized condition: "create"
```

it comes from [this line in `integrations/database/postgresql/install.sh`. ](https://github.com/kubearchive/kubearchive/blob/main/integrations/database/postgresql/install.sh#L19).

**Comment by skoved** [comment]
I missed the kubectl >= 1.31 in development.md

**Comment by maruiz93** [comment]
Maybe it's good to include this in the "known issues" section of the `DEVELOPMENT.md`

**Comment by rh-hemartin** [comment]
> Maybe it's good to include this in the "known issues" section of the `DEVELOPMENT.md`

I would rather add a check in the script if it comes to it, but if we keep our tools updated there shouldn't be any issues.

**Comment by maruiz93** [comment]
> add a check in the script
Actually I like this better.
At some point I guess people won't have older `kubectl` versions but now is something that could easily happen as it requires the latest minor version AFAIK, and the error that it returns it's not clear.

**Comment by ggallen** [comment]
> requires the latest minor version AFAIK

There's never been a new major release of `kubectl`.  It's at 1.x and all the releases are minor.

I don't see this as any different that the minimum `go` version.  Are we going to check for that in the scripts too?

In general, your `kubectl` version is supposed to be within two of the kubernetes version. So I expect you should regularly be updating you `kubectl` anyway.

**Comment by maruiz93** [comment]
ok then, I just wanted to prevent any more people falling into the same issue (I went through it the same way as @skoved, so I guessed is not that unusual for a newcommer) and although the requirement is in place, I think it's easy to miss
