### ISSUE TITLE
Improve failure message on database connection error

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#498]
Currently KubeArchive does not provide a useful message when it fails to connect to the database. We had a problem installing on a cluster where the Secret was populated in the following way:

```
POSTGRES_DB: ""
POSTGRES_DATABASE: "<database-name>"
```

This is wrong, because the correct key is `POSTGRES_DB` and should be populated. This problem yielded the following error:

```
$ kubectl logs -n kubearchive deployments/kubearchive-api-server
2024/10/02 13:18:42 Starting KubeArchive API with version 'v0.1.0', commit SHA '5b0ad85924e4b50a033f1980fbaac64a1a448d01', built '2024-09-06T07:33:30Z'
2024/10/02 13:18:42 Retry request 1, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/02 13:18:43 Retry request 2, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/02 13:18:45 Retry request 3, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/02 13:18:49 Retry request 4, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/02 13:18:57 Retry request 5, get error: dial tcp [::1]:5432: connect: connection refused
```

Which led us to think that there was another error other than the database name. I think KubeArchive can do better.

**Acceptance Criteria**

* Reproduce this in the current code.
* Make the error yield the URL, port, database used to establish the connection.
* Don't print the password.
* I'm not sure about printing the user.

**Comment by ggallen** [comment]
I have said this before, but we shouldn't have any empty strings for any of the database connection properties.  Nor do I think we should have `<database-name`.

All the values should be set to our development settings.  You may get a better error message then.

**Comment by rh-hemartin** [comment]
> I have said this before, but we shouldn't have any empty strings for any of the database connection properties. 

We do, this is v0.1.0 where we didn't provide default values for them.

> All the values should be set to our development settings. You may get a better error message then.

You are right, testing with a wrong database name (and all the other values OK) with v0.2.0 yields:

```
$ kubectl logs -n kubearchive deployments/kubearchive-sink
2024/10/03 05:27:35.864361 Starting KubeArchive Sink with version 'v0.2.0', commit SHA 'aef4220f58c10914277c2ba791e9a3680ad927c8', built '2024-10-02T11:43:34Z'
2024/10/03 05:27:35 Retry request 1, get error: pq: database "kubearchive" does not exist
2024/10/03 05:27:36 Retry request 2, get error: pq: database "kubearchive" does not exist
```

However if the DB is an empty string, it yields:

```
$ kubectl logs -n kubearchive deployments/kubearchive-sink
2024/10/03 05:26:58.479012 Starting KubeArchive Sink with version 'v0.2.0', commit SHA 'aef4220f58c10914277c2ba791e9a3680ad927c8', built '2024-10-02T11:43:34Z'
2024/10/03 05:26:58 Retry request 1, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/03 05:26:59 Retry request 2, get error: dial tcp [::1]:5432: connect: connection refused
2024/10/03 05:27:01 Retry request 3, get error: dial tcp [::1]:5432: connect: connection refused
```

Wrong URL:

```
$ kubectl logs -n kubearchive deployments/kubearchive-sink
2024/10/03 05:42:22.788422 Starting KubeArchive Sink with version 'v0.2.0', commit SHA 'aef4220f58c10914277c2ba791e9a3680ad927c8', built '2024-10-02T11:43:34Z'
2024/10/03 05:42:22 Retry request 1, get error: dial tcp: lookup non-existent.postgresq.svc.cluster.local on 10.96.0.10:53: no such host
2024/10/03 05:42:23 Retry request 2, get error: dial tcp: lookup non-existent.postgresq.svc.cluster.local on 10.96.0.10:53: no such host
```

I tested some combinations of empty and/or wrong values. For wrong values the errors tend to be OK, with empty values there are some problems.

**Comment by rh-hemartin** [comment]
Since this error is prevented by having default values as we have now, I don't think we should implement anything for it. If it happens too much users will complain and we will implement something. Closing.
