### ISSUE TITLE
The authorization cache key is only the user when it should be user+group+version+ns+action

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#502]
If the first SAR allows the user to perform the action, the user will be allowed to do whatever request afterwards until the cache expires.

The same happens the other way around, if the first request of the user is denied, by a SAR, the rest of the requests of the user will be denied even if they have permission to do it.

I believe we should store in the key cache all the following params:
* user
* group
* version
* namespace
* action

**Comment by rh-hemartin** [comment]
I was thinking this while I was reviewing your PR about changing the verb for the SAR. This makes sense to me.
