### ISSUE TITLE
Investigate the impact of deserializing JSON in the API answer

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#504]
Currently when we return an answer from the API the process queries the database and then deserializes the JSON into a `unstructured.Unstructured` struct using `json.Unmarshal`.  This process happens for all objects returned, but we don't do anything with the objects. Investigate the cost of this unmarshalling using benchmarks with Go.

**Acceptance Criteria**

* Use Go benchmarking (and maybe other more rudimentary tools) to see the performance of serializing vs not-deserializing.
* Don't change the API answer code yet, we just want information.

Notes:

* It does not even need to be in our code, maybe a script that does it and that it mimics what do we do could be enough.
* Make sure its the closest possible so we get a reasonable comparison.
* The best scenario is to run this in our code, so we get the "real" comparison.
* This may be OK with queries that are limited in size, but probably is worth optimizing for very large queries.

**Comment by rh-hemartin** [comment]
I ran some tests with locust. Looks like there is some impact when there are resources on the database. I have to check if all the increase in time is due to DB latency, or us deserializing.

```
`locust --headless --users 1 -r 1 -t 30s -H https://localhost:8081 --processes 1 GetPods`

*0 on database*

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /api/v1/pods                                                                   22264     0(0.00%) |      1       1      32      1 |  741.36        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     22264     0(0.00%) |      1       1      32      1 |  741.36        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods                                                                            1      1      1      1      2      2      2      2      3      6     32  22264
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                              1      1      1      1      2      2      2      2      3      6     32  22264

*100 on database*

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /api/v1/pods                                                                     190     0(0.00%) |    156     100     300    120 |    6.38        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                       190     0(0.00%) |    156     100     300    120 |    6.38        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods                                                                          130    190    200    200    210    290    290    300    300    300    300    190
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            130    190    200    200    210    290    290    300    300    300    300    190

*10_000 on database*

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /api/v1/pods                                                                     197     0(0.00%) |    151      69     300    140 |    6.58        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                       197     0(0.00%) |    151      69     300    140 |    6.58        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods                                                                          140    170    170    190    200    230    270    270    300    300    300    197
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            140    170    170    190    200    230    270    270    300    300    300    197

* 10_000 on database, limit=1000

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /api/v1/pods?limit=1000                                                           18     0(0.00%) |   1600    1294    2000   1600 |    0.62        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                        18     0(0.00%) |   1600    1294    2000   1600 |    0.62        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods?limit=1000                                                              1700   1700   1700   1800   1800   2000   2000   2000   2000   2000   2000     18
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                           1700   1700   1700   1800   1800   2000   2000   2000   2000   2000   2000     18
         

* 10_000 on database, limit=1

Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /api/v1/pods?limit=1                                                           12554     0(0.00%) |      2       1      56      2 |  417.85        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     12554     0(0.00%) |      2       1      56      2 |  417.85        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods?limit=1                                                                    2      2      2      2      2      3     12     17     29     34     57  12554
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                              2      2      2      2      2      3     12     17     29     34     57  12554
```

**Comment by maruiz93** [comment]
For those that aren't sure of how to read the posted results:

* `avg` (average),` min` and `max` are the time that the request took in milliseconds
* the percentile table is read as: the `x`% of the requests are solved in less than `y` milliseconds

e.g.

```
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v1/pods?limit=1000                                                              1700   1700   1700   1800   1800   2000   2000   2000   2000   2000   2000     18
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                           1700   1700   1700   1800   1800   2000   2000   2000   2000   2000   2000     18
         
```

The 95% of the requests made take less than 2 seconds

**Comment by rh-hemartin** [comment]
To add a little bit more: usually the target percentile is 95% or 99%. The idea is that you want most of requests to take less than X, so normally you monitor those high percentiles to ensure most of people will be happy with their response times.

**Comment by maruiz93** [comment]
After reading about serialize/deserialize json performance it seems that there are several libraries for dealing with these operations faster than the `encoding/json` native library.

Just for reference, in case we want to keep the deserialization while keeping it performant:

* Alternative libraries:
  * https://github.com/json-iterator/go
  * https://github.com/bytedance/sonic 
  * https://github.com/mailru/easyjson 
  * https://github.com/goccy/go-json 
  * https://github.com/pquerna/ffjson
  * https://github.com/segmentio/encoding

* Benchmark tests that compare some of them
  * https://github.com/go-json-experiment/jsonbench

Considering the speed, the size and the maintenance of  the project my first two picks if we want to test different performance would be: 
1. https://github.com/bytedance/sonic
2. https://github.com/json-iterator/go

Note that the structure of the deserialized objects is important when measuring performance so, in case we want to change the native `encoding/json` library to another library we should do our own performance test

**Comment by ggallen** [comment]
> Currently when we return an answer from the API the process queries the database and then deserializes the JSON into a unstructured.Unstructured struct using json.Unmarshal. This process happens for all objects returned, but we don't do anything with the objects.

I have to ask this:  if  don't do anything with these deserialized objects, then why are we deserializing them?

Also, we should not be making any performance decisions based on a database containing 10K objects. That size is so small that the difference in the sizes being tested here is really negligible.  We should be using the 7.8 million record database for testing.  Maybe we'll find out the performance is the same, but if we see a performance impact from 0 records to 10K records, it's likely that millions of records will be worse. Maybe it levels out at some point, but we need to know this.

**Comment by maruiz93** [comment]
> I have to ask this: if don't do anything with these deserialized objects, then why are we deserializing them?

I initially introduced the deserialization on retrieval because it made sense to me from a logical POV (let's retrieve a list of resources and not a random JSON) and also because I expect we will need that for supporting some things that the Kubernetes API support like [retrieving the information in a table format](https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables).

This is something that isn't used yet, so we could directly remove the deserialization and just return JSONs for now (and I believe that this ticket was opened to check if we should do that change), but I think we should keep in mind that we might want to use deserialization at some point.

**Comment by ggallen** [comment]
> This is something that isn't used yet, so we could directly remove the deserialization and just return JSONs for now (and I believe that this ticket was opened to check if we should do that change), but I think we should keep in mind that we might want to use deserialization at some point.

I find your view here at odds with the one you've taken in https://github.com/kubearchive/kubearchive/pull/609#discussion_r1833528674!  :-)

**Comment by maruiz93** [comment]
> I find your view here at odds with the one you've taken in https://github.com/kubearchive/kubearchive/pull/609#discussion_r1833528674

Hmm, I don't see it that way. In that comment I am giving priority to the number of queries done (read operations) over "readability" (although I don't think that the code looked that bad or was that complex, maybe that's because I am too close to it) but here I am open to remove something that isn't performant although I believe we may want to support features that need the objects to be deserialized (doing more queries isn't needed for any current or potential future feature, that's why I see it different)

**Comment by rh-hemartin** [comment]
> We should be using the 7.8 million record 

I tested with the 7.8 million records and the performance is worse overall.

**Comment by maruiz93** [comment]
> I tested with the 7.8 million records and the performance is worse overall.

We may have two problems then, but I believe that we should isolate each thing to get useful conclusions. For example, using a mock driver database that has fixed data and returns the requested number of items to test how bad is the deserializing problem.

**Comment by ggallen** [comment]
I'm not sure why we are wasting time testing the performance of something we don't need and probably should not be doing. If we need it in the future, we can investigate it then.  If it's a performance problem now, we should take it out.
