### ISSUE TITLE
Refactor the errors sent to abort.Abort()

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#536]
In the API Server we have defined a helper function [Abort](https://github.com/kubearchive/kubearchive/blob/main/cmd/api/abort/abort.go#L12) to log an error and set it properly as an HTTP Response with the proper HTTP Status code.

The signature of the code currently receives a `msg` string parameter but it should receive an error.

This way, the responsibility of properly formatting the message of the error is encapsulated in the `Abort` function and not spread out in the callers.

All the callers of this function should pass an error with a message that follows the [error string format](https://google.github.io/styleguide/go/decisions.html#error-strings):
* No dot at the end
* No capitalized

**Acceptance Criteria**:
* Refactor the signature of Abort to receive an Error instead of a string message
* Adjust the callers properly

**Comment by rh-hemartin** [comment]
> This way, the responsibility of properly formatting the message of the error is encapsulated in the Abort function and not spread out in the callers.

This does not get reflected in the acceptance criteria and sounds like it is an acceptance criteria. Sounds like you want `abort.Abort` to capitalize and add a trailing dot to the error message it receives.

**Comment by ggallen** [comment]
The routine should also check that the HTTP error code is acceptable.
