### ISSUE TITLE
Refactor the methods of the Database interface

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#537]
The [DBInterface](https://github.com/kubearchive/kubearchive/blob/main/pkg/database/database.go#L28) currently has methods whose implementations are really similar:

* `QueryResources` & `QueryCoreResources`
* `QueryNamespacedResources` & `QueryNamespacedCoreResources`
* `QueryNamespacedResourceByName` & `QueryNamespacedCoreResourceByName`

A core resource and a non-core resource only differentiate on the apigroup, core resources don't have group, just version (e.g. `v1`) while non-core resources have both (e.g. `apps/v1`)

We are starting to have duplicated code and we need to figure out if we want to keep having separated methods on the interface and use private methods to handle the duplicated logic or merge those methods and just receive an "apiGroup", which makes sense considering that in kubernetes you don't explicitly differentiate core and non-core resources.

EDIT based on the decided path:

**Acceptance Criteria**:
* Remove `QueryCoreResources` in favor of `QueryResources`
* Remove `QueryNamespacedCoreResources` in favor of `QueryNamespacedResources`
* Remove `QueryNamespacedCoreResourceByName` in favor of `QueryNamespacedResourceByName`
* Merge the parameters `group` and `version` of these methods to `apiVersion`
* Move the logic of building the `apiversion` from `group` and `version` to the callers

**Comment by rh-hemartin** [comment]
I would extract the `apiVersion := fmt.Sprintf("%s/%s", group, version)` to the handler and just use `QueryCoreResources` renamed to `QueryResources`. The same goes for their namespaced versions. It makes sense that the database layer does not know that group and version make apiversion, but it makes sense that the handler does.

Also, doing another level of functions as I understood you proposed:

handleCoreResources -> QueryCoreResouces -> queryResources
handleResources -> QueryResources (apiVersion=group+version) -> queryResources

Looks like an overkill when you could do the logic in the handler instead:

handleCoreResources  -> QueryResources
handleResouces (apiVersion=group+version) -> QueryResouces

**Comment by maruiz93** [comment]
I agree on going with the merge of `QueryCoreResources` + `QueryResources` and `QueryNamespacedResources` + `QueryNamespacedCoreResources` as we are doing the separation because we are following the endpoints structure of Kubernetes, not because KubeArchive need that differentiation for anything.
