### ISSUE TITLE
API server should allow retrieval log URLs

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#539]
The CLI and API server should allow the user to retrieve log URLs associated with archived resources.

Although logs are associated with `Pods`, the log URLs should be able to be retrieved by referencing any `Pod` owner.  For example, if the user asks for logs for a ` PipelineRun`, the API server needs to query the database to get the logs from all `Pods` that executed as part of that `PipelineRun`.

A query to retrieve resources that are owned by another resource might look like this:

```
SELECT uuid
FROM public.resource
WHERE data->'metadata'->'ownerReferences' @> '[{"uid": "2d893024-4ed4-4318-a12d-13cb7f6562bc'"}]'::jsonb;
```

The API server may need to make multiple queries to retrieve all the `Pods` and then get the log URLs.  Or a stored procedure could be created to do all the work, resulting in only a single call being required from the API server.

### Acceptance Criteria

1. The API server ~and CLI~ allows users to query and retrieve log URLs.

NOTE: the CLI part is addressed in a separate issue with its own PR

### References

- [Logging design document](https://github.com/kubearchive/kubearchive/blob/main/docs/modules/ROOT/pages/design/logging-integration.adoc)
- This is dependent upon log URL generation functionality in the sink (see https://github.com/kubearchive/kubearchive/issues/538)
- This issue relates to https://github.com/kubearchive/kubearchive/issues/492.

**Comment by maruiz93** [comment]
The whole log URL retrieval feature is big enough to be separated into several issues.

I linked the main PR to this issue but I am creating separate issues to get this feature complete:

https://github.com/kubearchive/kubearchive/issues/633 
https://github.com/kubearchive/kubearchive/issues/632
https://github.com/kubearchive/kubearchive/issues/631 
https://github.com/kubearchive/kubearchive/issues/630
