### ISSUE TITLE
Default can't create tokenreviews

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#54]
When I follow the DEVELOPMENT.md guide, I get the following error trying to query the API. I'm using a fake token. However the problem resides on the API, which is not being able to check if the token is correct. Looks like the pod running the API is not using the proper service account to run, so it tries to do operations with the default service account.

# Error log
```
$ curl -H "Authorization: Bearer abcd"  localhost:8081/apis/apps/v1/deployments
{"message":"Unexpected error on TokenReview: tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:kubearchive:default\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope"}
```

# Steps to reproduce
```
kind create cluster
export KO_DOCKER_REPO="kind.local"
helm install kubearchive charts/kubearchive \
    --set-string apiServer.image=$(ko build github.com/kubearchive/kubearchive/cmd/api) \
    --set-string sink.image=$(ko build github.com/kubearchive/kubearchive/cmd/sink)
kubectl run -n test busybox --image=busybox
kubectl port-forward -n kubearchive svc/kubearchive-api-server 8081:8081 &
curl -H "Authorization: Bearer abcd" localhost:8081/apis/apps/v1/deployments
```

**Comment by maruiz93** [comment]
This issue should be covered with: https://github.com/kubearchive/kubearchive/issues/42. I'm currently working on it, I think we can close this issue as a duplicate.
