### ISSUE TITLE
Introduce an .editorconfig file

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#57]
We found ourselves with mix and match indentation due to different IDEs getting different clues for indenting files. An .editorconfig file should reduce the number of problems we have with different indentation practices. Stuff to include in the editorconfig:

* End of line: LF
* Markdown indentation: 4 spaces
* Golang indentation: 1 tab
* Trim trailing spaces
* Add newline at the end of the file

**Comment by skoved** [comment]
I think everything here makes sense. On top of this I think we should enable `gofmt` in golangci-lint. This will enforce the golang style rules on all *.go files (not just hard tabs instead of spaces).
