### ISSUE TITLE
Results should be from new to old

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#586]
Curerntly the results are returned by the API from old entries to new entries, we want to return the new entries first, then the old ones. This is because the default sort for columns is ASC, and we want DESC. I didn't notice when I implemented the pagination (which introduced sorting for the first time).

I did play around with using DESC in the ORDER BY clause, but the uuid column is resisting to be tamed and no matter if the WHERE clause of `(timestamp, uuid) < (value, value)` is kept toghether or we split it `timestamp < value AND uuid > value` the results are not consistent. Yoou should be able to reproduce with +200 objects. Get the first page with 100, then the second page. Then get a page with 200 elements. page 1 + page 2 should equal the page with 200 objects. If you start doing comparison on uuids you will see there are overlappings or entries missed when using DESC.

We checked with a couple of database-knowledgeable people and they recommended us to not use UUIDv4 to sort because its fundamentally unsortable, as its random. They suggested to move to a autincremental ID to use in the pagination so we don't miss entries.

The point of this PR is that we change the return of the objects so the new are returned first. However that requires changing the UUIDv4 to something else. So:

**Acceptance Criteria**

* Return resources from new to old, so invert the current order with `DESC`.
* Introduce a BIGSERIAL as primary key for the `resource` table and use it for ordering alongside the creationTimestamp.

Additionaly:

* Introduce a BIGSERIAL as primary key for the table `log_url` as well.

Edit: changed SERIAL for BIGSERIAL

**Comment by ggallen** [comment]
> Introduce a SERIAL as primary key
Let's use `BIGSERIAL`.
