### ISSUE TITLE
Add container name to log_url table and populate it from the sink.

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#605]
As noted in [this comment](https://github.com/kubearchive/kubearchive/pull/576#pullrequestreview-2407485221), KubeArchive needs to allow the retrieval of log URLs by container name.  This currently isn't possible as the container name is embedded in the JSON blob.

The `log_url` table should have a new column named `container_name`, which should be populated by the sink when the records are inserted.

### Acceptance Criteria:

- A column named `container_name` is added to the `log_url` table.
- The sink populates the `log_url.container_name` column when inserting log URL records.

**Comment by skoved** [comment]
how is the sink supposed to know what container a log url is for?

**Comment by skoved** [comment]
also, I noticed that we don't have a `log_url` table defined for mariadb. I created an issue to add that table #606

**Comment by skoved** [comment]
> how is the sink supposed to know what container a log url is for?

I think what I'm going to do is create a new type that contains a url (string) and containerName (string) and `log_urls.GenerateLogURLs` will return a slice of this new type instead of `[]string`

**Comment by skoved** [comment]
> how is the sink supposed to know what container a log url is for? I'm not sure where either the sink or `log_urls.GenerateURLs` know for sure which container a url was generated for

What makes the most sense to me is making `CONTAINER_NAME` required in the logging `ConfigMap` and having `log_urls.GenerateURLs` return a slice of structs with Url and ContainerName fields and then passing this slice to `Database.WriteUrls`

**Comment by ggallen** [comment]
> how is the sink supposed to know what container a log url is for? I'm not sure where either the sink or `log_urls.GenerateURLs` know for sure which container a url was generated for

Great question. I didn't think of that.  I agree we can change the return from generating log URLs to include this information.  Can you open a ticket and I'll take it?  If I don't open the ticket first.

**Comment by skoved** [comment]
>   I agree we can change the return from generating log URLs to include this information. Can you open a ticket and I'll take it? If I don't open the ticket first.

I included  this change in my PR for this issue. If you want a seperate issue, I can still open one and link it to my existing PR

**Comment by ggallen** [comment]
No. I saw your changes after I made this comment.  Let's not hold things up.
