### ISSUE TITLE
Introduce documentation

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#68]
The project needs documentation. I have some alternatives for how to organize the documentation url and repository-wise:

1. Hosted at https://kubearchive.github.io/, documentation lives between the repositories kubearchive.github.io (pulls kubearchive) and kubearchive (where the docs live).
1. Hosted at https://kubearchive.github.io/, all documentation lives on the kubearchive.github.io repository.
1. Hosted at https://kubearchive.github.io/kubearchive, all documentation lives on the kubearchive repository.

The kubearchive.github.io repository is needed to host at root level (`/`) on https://kubearchive.github.io/ . However that complicates a little the setup if we want to keep the code and the documentation on the same repository (kubearchive). The dual repository complicates the release, as the kubearchive repository will need to schedule a workflow in the kubearchive.github.io repository to generate the site.

I think the option 3 is the way to go, as we keep documentation in the same repository as code, reducing complexity and the only thing bad thing is that we show the documentation on `https://kubearchive.github.io/kubearchive/` instead.

What do you think?

**Comment by ggallen** [comment]
I don't understand the differences between the options.

**Comment by rh-hemartin** [comment]
> I don't understand the differences between the options.

The difference is between having one or two repositories to manage the documentation and having to serve the documentation in https://kubearchive.github.io/ vs serving it under https://kubearchive.github.io/kubearchive.
