### ISSUE TITLE
Store JSONPath in along the log url in the database

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#689]
### Context

We currently store the `url` in the `log_url` table and avoid building the url on retrieval instead of on insertion because that prevents having wrong old urls. E.g, if the logging backend system changes, the new pods will have the new log urls while the old ones will keep the old system, so the information is still "correct". 
Now that we have a new element in place, the JSONPath to be able to parse the logs retrieved from the logging system, following the same logic we should store it in the database.

Another advantage of this design is that the `kubearchive-logging` configmap is only coupled to the sink but not to both sink and api.

### Acceptance Criteria

* Store the JSONPath along the `url` in a new column of the `log_url` database table.

**Comment by skoved** [comment]
I add the database label since this will also require adding a `jsonpath` column to the `log_url` table.

I'm willing to it to the `log_url` table. My only hangup on this would be the about what happens if the jsonpath changes but you pointed out that the actual url is handled this way
