### ISSUE TITLE
Renovate is running on forks

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#74]
The renovate workflow is running on my fork, which maybe is fine. But its trying to generate a one time token for the KubeArchive APP, however it fails because the secrets needed to retrieve that token do not exist.

Failed Renovate Workflow: https://github.com/rh-hemartin/kubearchive/actions/runs/9544446134/job/26303141135

How do I solve this? Should the workflow be skipped on forks?

**Comment by skoved** [comment]
It should be skipped on forks since on the main kubearchive repo is configured to have a token generated. I'll figure out how to make the action skip running on forks

**Comment by skoved** [comment]
looks like i can add a conditional stop the action from running in forks `if: github.repository != 'kubearchive/kubearchive'`

**Comment by rh-hemartin** [comment]
> looks like i can add a conditional stop the action from running in forks `if: github.repository != 'kubearchive/kubearchive'` or maybe `if: github.repository == 'kubearchive/kubearchive'`

Sounds like a good fix.
