### ISSUE TITLE
the api server should be able to read resources out of the database

### ISSUE THREAD

**Issue by skoved** [kubearchive/kubearchive#78]
The api server should be able to lookup kubernetes resources that have been written into the database by the sink. Since this is geared towards to the demo, it might be enough to either look for a specific resource by name or get all resources of a certain kind depending on time constraints.

**Comment by skoved** [comment]
I started working on #77 and plan to use [gorm](https://gorm.io/index.html) to write resources into the database so I think that the sink and api server should share models. They could be placed in somewhere like `pkg/database/models`

**Comment by rh-hemartin** [comment]
I don't think we need to use `gorm` for now. It comes with a lot of assumptions and practices we may not need. For our use case which is a single table, so a single model, I don't think using it has many benefits. We won't do any table operations, not do any model relation, etc. just selects and inserts.

I think we should use the bare-bone driver and then see how it works and see what do we need. What do you think?
