### ISSUE TITLE
Update the database schema

### ISSUE THREAD

**Issue by mafh314** [kubearchive/kubearchive#86]
Add the missing fields to the metadata table and create a separate table for the json data.

**Comment by rh-hemartin** [comment]
Can you elaborate a bit more in the description about what you propose?

**Comment by ggallen** [comment]
I think the only reason for the separate tables is because that's what the design has in the miro board, which we inherited.

I suspect @mafh314 is following that, as I was when I generated some sample SQL for her.

**Comment by mafh314** [comment]
That's right @ggallen. I wanted to follow the desing that we have in the miro board.

**Comment by mafh314** [comment]
@rh-hemartin I will modify the schema to add the missing fields from the miro board diagram but we will have only one table.

**Comment by rh-hemartin** [comment]
> @rh-hemartin I will modify the schema to add the missing fields from the miro board diagram but we will have only one table.

Having one table is better for me, so perfect. About the other fields, I'm not sure which they are. Could you list the fields you intend to introduce so we can discuss about them?

**Comment by mafh314** [comment]
@rh-hemartin The changes would be:
- rename the table from `test_objects` to `Resource`.
- add the field: `cluster_delete_ts` (Timestamp) NULL.
- add the field: `cluster` (varchar) NOT NULL.
- add the field: `cluster_uid` (varchar) NOT NULL.

**Comment by ggallen** [comment]
Why both `cluster` and `cluster_uuid`?

I think the naming conventions for postgres are all lower case using underscores.  So `resource` or `archive_meta`. I believe this applies to all database things like table and column names, etc.

**Comment by mafh314** [comment]
@ggallen you're right about the lower case. In the PR the table name is `resource`. 

> Why both cluster and cluster_uuid?
I think that cluster will be use to create index. And since the cluster name is not unique we need to add the cluster_uid.  These fields are from the initial DB design. But we can talk about them in the sync meeting.

Changes:
    rename the table from test_objects to resource.
    add the field: cluster_delete_ts (Timestamp) NULL.
    add the field: cluster (varchar) NOT NULL.
    add the field: cluster_uid (uuid) NOT NULL.

**Comment by skoved** [comment]
> Why both `cluster` and `cluster_uuid`?
> 
> I think the naming conventions for postgres are all lower case using underscores. So `resource` or `archive_meta`. I believe this applies to all database things like table and column names, etc.

If I remember correctly, cluster is the name of the `cluster` that the resource was created in and `cluster_uid` is value of the resource's `.metadata.uid` field which is the value the will distinguish that specific resource from an other resource of the same type that gets created in the same namespace, with the same name. Since kubearchive will eventually delete resources from the cluster these types of collisions will become possible, so we need to have a way to uniquely identify a resource
